---
name: Caching test


description: |
  Composite action used to test disable-cache mechanism
  based on chat-ops command and PR labels

runs:
  using: composite
  steps:
      # Check if PR contains a label to disable the cache
    - name: Check if cache is enabled
      uses: ./.github/actions/is-cache-enabled
      id: is-cache-enabled

    - name: Cache local Maven repository
      # Only use the full cache action if we're on main or stable/* branches
      if: ${{ startsWith(github.ref_name, 'stable/') || github.ref_name == 'main' }}
      shell: sh
      run: |
        echo "Saving cache"

    - name: Restore maven cache
      # Restore cache (but don't save it) if we're not on main or stable/* branches or cache is not disabled
      if: ${{ !(startsWith(github.ref_name, 'stable/') || github.ref_name == 'main') && steps.is-cache-enabled.outputs.is-cache-enabled == 'true' }}
      env:
        PAYLOAD_DUMP: ${{ toJSON(steps.is-cache-enabled) }}
      shell: sh
      run: |
        echo "$PAYLOAD_DUMP"
        echo "Restoring cache"
