---
name: chatops-command-disable-cache

on:
  repository_dispatch:
    types: [disable-cache-command, enable-cache-command]

env:
  NO_CACHE_LABEL: "ci:no-cache"

jobs:
  chatops-command-disable-cache:
    permissions: write-all
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Create URL to the run output
      id: vars
      run: |
        {
        echo "run_url=https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
        } >> "$GITHUB_OUTPUT"

    - name: Dump the client payload context
      env:
        PAYLOAD_CONTEXT: ${{ toJson(github.event.client_payload) }}
      run: echo "$PAYLOAD_CONTEXT"


    - name: Disable cache restoration
      id: disable-cache
      if: ${{ github.event.client_payload.slash_command.command == 'disable-cache' }}
      shell: bash
      env:
        GH_REPO: ${{ github.repository }}
        GH_TOKEN: ${{ github.token }}
        PR_NUMBER: ${{ github.event.client_payload.pull_request.number }}
        BRANCH: ${{ github.event.client_payload.pull_request.head.ref }}
      run: |
        if [[ -n "$PR_NUMBER" ]]; then
            gh pr edit "$PR_NUMBER" --add-label "$NO_CACHE_LABEL"
            # echo "Checkout branch $BRANCH and pushing empty commit"
            # git fetch && git checkout "$BRANCH"
            # git commit --allow-empty -m "ci: REMOVEME" && git push
        else
          echo ":debug:Command was not executed on a PR"
        fi

    - name: Enable cache restoration
      id: enable-cache
      if: ${{ github.event.client_payload.slash_command.command == 'enable-cache' }}
      shell: bash
      env:
        GH_REPO: ${{ github.repository }}
        GH_TOKEN: ${{ github.token }}
        PR_NUMBER: ${{ github.event.client_payload.pull_request.number }}
        BRANCH: ${{ github.event.client_payload.pull_request.head.ref }}
      run: |
        if [[ -n "$PR_NUMBER" ]]; then
            gh pr edit "$PR_NUMBER" --remove-label "$NO_CACHE_LABEL"
            # echo "Checkout branch $BRANCH and pushing empty commit"
            # git fetch && git checkout "$BRANCH"
            # git commit --allow-empty -m "ci: REMOVEME" && git push
        else
          echo ":debug:Command was not executed on a PR"
        fi

    - name: Add reaction
      uses: peter-evans/create-or-update-comment@v4
      with:
        token: ${{ secrets.PAT }}
        repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
        comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
        reactions: "+1"
        reactions-edit-mode: replace
          #
    # - name: Git User Setup
    #   run: |
    #     git config --global user.email "github-actions"
    #     git config --global user.name "github-actions@users.noreply.github.com"

    - uses: actions/checkout@v4
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0             # otherwise, you will fail to push refs to dest repo

    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.PAT }}

    - name: Update comment in case of failure
      if: failure()
      uses: peter-evans/create-or-update-comment@v4
      with:
        token: ${{ secrets.PAT }}
        comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
        body: |
          > Had issues fulfilling your command, check the [logs](${{ steps.vars.outputs.run_url }})
        reactions: confused
