name: Workflow dispatch

on:
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      # Detect changes against the base branch
      - name: Cache testing
        uses: ./.github/actions/caching


